package vn.com.vti.bookshop.entity;

public class BusinessType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.business_type.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.business_type.business_type_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String businessTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.business_type.id
     *
     * @return the value of public.business_type.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.business_type.id
     *
     * @param id the value for public.business_type.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.business_type.business_type_name
     *
     * @return the value of public.business_type.business_type_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getBusinessTypeName() {
        return businessTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.business_type.business_type_name
     *
     * @param businessTypeName the value for public.business_type.business_type_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setBusinessTypeName(String businessTypeName) {
        this.businessTypeName = businessTypeName;
    }
}