package vn.com.vti.bookshop.entity;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.category.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.category.category_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String categoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.category.id
     *
     * @return the value of public.category.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.category.id
     *
     * @param id the value for public.category.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.category.category_name
     *
     * @return the value of public.category.category_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.category.category_name
     *
     * @param categoryName the value for public.category.category_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
}