package vn.com.vti.bookshop.entity;

public class JobType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.job_type.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.job_type.job_type_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String jobTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.job_type.id
     *
     * @return the value of public.job_type.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.job_type.id
     *
     * @param id the value for public.job_type.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.job_type.job_type_name
     *
     * @return the value of public.job_type.job_type_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getJobTypeName() {
        return jobTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.job_type.job_type_name
     *
     * @param jobTypeName the value for public.job_type.job_type_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setJobTypeName(String jobTypeName) {
        this.jobTypeName = jobTypeName;
    }
}