package vn.com.vti.bookshop.entity;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.password
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.last_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.first_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.post_code
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.address
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.birthday
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.tel_no
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String telNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.mail_address
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String mailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.regist_datetime
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Date registDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.member_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String memberType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.blood_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String bloodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.child_name1
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String childName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.child_name2
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String childName2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.child_name3
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String childName3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.business_type_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer businessTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.job_type_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer jobTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.id
     *
     * @return the value of public.member.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.id
     *
     * @param id the value for public.member.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.password
     *
     * @return the value of public.member.password
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.password
     *
     * @param password the value for public.member.password
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.last_name
     *
     * @return the value of public.member.last_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.last_name
     *
     * @param lastName the value for public.member.last_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.first_name
     *
     * @return the value of public.member.first_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.first_name
     *
     * @param firstName the value for public.member.first_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.post_code
     *
     * @return the value of public.member.post_code
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.post_code
     *
     * @param postCode the value for public.member.post_code
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.address
     *
     * @return the value of public.member.address
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.address
     *
     * @param address the value for public.member.address
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.birthday
     *
     * @return the value of public.member.birthday
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.birthday
     *
     * @param birthday the value for public.member.birthday
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.tel_no
     *
     * @return the value of public.member.tel_no
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.tel_no
     *
     * @param telNo the value for public.member.tel_no
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.mail_address
     *
     * @return the value of public.member.mail_address
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.mail_address
     *
     * @param mailAddress the value for public.member.mail_address
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.regist_datetime
     *
     * @return the value of public.member.regist_datetime
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Date getRegistDatetime() {
        return registDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.regist_datetime
     *
     * @param registDatetime the value for public.member.regist_datetime
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setRegistDatetime(Date registDatetime) {
        this.registDatetime = registDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.member_type
     *
     * @return the value of public.member.member_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.member_type
     *
     * @param memberType the value for public.member.member_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setMemberType(String memberType) {
        this.memberType = memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.blood_type
     *
     * @return the value of public.member.blood_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.blood_type
     *
     * @param bloodType the value for public.member.blood_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.child_name1
     *
     * @return the value of public.member.child_name1
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getChildName1() {
        return childName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.child_name1
     *
     * @param childName1 the value for public.member.child_name1
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setChildName1(String childName1) {
        this.childName1 = childName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.child_name2
     *
     * @return the value of public.member.child_name2
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getChildName2() {
        return childName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.child_name2
     *
     * @param childName2 the value for public.member.child_name2
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setChildName2(String childName2) {
        this.childName2 = childName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.child_name3
     *
     * @return the value of public.member.child_name3
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getChildName3() {
        return childName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.child_name3
     *
     * @param childName3 the value for public.member.child_name3
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setChildName3(String childName3) {
        this.childName3 = childName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.business_type_id
     *
     * @return the value of public.member.business_type_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getBusinessTypeId() {
        return businessTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.business_type_id
     *
     * @param businessTypeId the value for public.member.business_type_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setBusinessTypeId(Integer businessTypeId) {
        this.businessTypeId = businessTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.job_type_id
     *
     * @return the value of public.member.job_type_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getJobTypeId() {
        return jobTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.job_type_id
     *
     * @param jobTypeId the value for public.member.job_type_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setJobTypeId(Integer jobTypeId) {
        this.jobTypeId = jobTypeId;
    }
}