package vn.com.vti.bookshop.entity;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.order_detail_no
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer orderDetailNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.item_num
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer itemNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.item_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.order_header_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer orderHeaderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.id
     *
     * @return the value of public.order_detail.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.id
     *
     * @param id the value for public.order_detail.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.order_detail_no
     *
     * @return the value of public.order_detail.order_detail_no
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getOrderDetailNo() {
        return orderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.order_detail_no
     *
     * @param orderDetailNo the value for public.order_detail.order_detail_no
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setOrderDetailNo(Integer orderDetailNo) {
        this.orderDetailNo = orderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.item_num
     *
     * @return the value of public.order_detail.item_num
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getItemNum() {
        return itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.item_num
     *
     * @param itemNum the value for public.order_detail.item_num
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setItemNum(Integer itemNum) {
        this.itemNum = itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.item_id
     *
     * @return the value of public.order_detail.item_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.item_id
     *
     * @param itemId the value for public.order_detail.item_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.order_header_id
     *
     * @return the value of public.order_detail.order_header_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getOrderHeaderId() {
        return orderHeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.order_header_id
     *
     * @param orderHeaderId the value for public.order_detail.order_header_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setOrderHeaderId(Integer orderHeaderId) {
        this.orderHeaderId = orderHeaderId;
    }
}