package vn.com.vti.bookshop.entity;

import java.util.Date;

public class OrderHeader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_header.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_header.order_datetime
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Date orderDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_header.payment_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String paymentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_header.member_card_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer memberCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_header.member_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_header.id
     *
     * @return the value of public.order_header.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_header.id
     *
     * @param id the value for public.order_header.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_header.order_datetime
     *
     * @return the value of public.order_header.order_datetime
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Date getOrderDatetime() {
        return orderDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_header.order_datetime
     *
     * @param orderDatetime the value for public.order_header.order_datetime
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setOrderDatetime(Date orderDatetime) {
        this.orderDatetime = orderDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_header.payment_type
     *
     * @return the value of public.order_header.payment_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_header.payment_type
     *
     * @param paymentType the value for public.order_header.payment_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_header.member_card_id
     *
     * @return the value of public.order_header.member_card_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getMemberCardId() {
        return memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_header.member_card_id
     *
     * @param memberCardId the value for public.order_header.member_card_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setMemberCardId(Integer memberCardId) {
        this.memberCardId = memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_header.member_id
     *
     * @return the value of public.order_header.member_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_header.member_id
     *
     * @param memberId the value for public.order_header.member_id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}