package vn.com.vti.bookshop.entity;

public class Publisher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.publisher.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.publisher.publisher_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String publisherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.publisher.prefecture
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    private String prefecture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.publisher.id
     *
     * @return the value of public.publisher.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.publisher.id
     *
     * @param id the value for public.publisher.id
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.publisher.publisher_name
     *
     * @return the value of public.publisher.publisher_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getPublisherName() {
        return publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.publisher.publisher_name
     *
     * @param publisherName the value for public.publisher.publisher_name
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.publisher.prefecture
     *
     * @return the value of public.publisher.prefecture
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public String getPrefecture() {
        return prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.publisher.prefecture
     *
     * @param prefecture the value for public.publisher.prefecture
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    public void setPrefecture(String prefecture) {
        this.prefecture = prefecture;
    }
}