package vn.com.vti.bookshop.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import vn.com.vti.bookshop.entity.JobType;
import vn.com.vti.bookshop.entity.JobTypeExample;

public interface JobTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.job_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    long countByExample(JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.job_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int deleteByExample(JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.job_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.job_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int insert(JobType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.job_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int insertSelective(JobType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.job_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    List<JobType> selectByExample(JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.job_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    JobType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.job_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByExampleSelective(@Param("record") JobType record, @Param("example") JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.job_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByExample(@Param("record") JobType record, @Param("example") JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.job_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByPrimaryKeySelective(JobType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.job_type
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByPrimaryKey(JobType record);
}