package vn.com.vti.bookshop.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import vn.com.vti.bookshop.entity.OrderDetail;
import vn.com.vti.bookshop.entity.OrderDetailExample;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    long countByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int deleteByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    List<OrderDetail> selectByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    OrderDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByExampleSelective(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByExample(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByPrimaryKeySelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByPrimaryKey(OrderDetail record);
}