package vn.com.vti.bookshop.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import vn.com.vti.bookshop.entity.OrderHeader;
import vn.com.vti.bookshop.entity.OrderHeaderExample;

public interface OrderHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    long countByExample(OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int deleteByExample(OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int insert(OrderHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int insertSelective(OrderHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    List<OrderHeader> selectByExample(OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    OrderHeader selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByExampleSelective(@Param("record") OrderHeader record, @Param("example") OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByExample(@Param("record") OrderHeader record, @Param("example") OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByPrimaryKeySelective(OrderHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByPrimaryKey(OrderHeader record);
}