package vn.com.vti.bookshop.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import vn.com.vti.bookshop.entity.Publisher;
import vn.com.vti.bookshop.entity.PublisherExample;

public interface PublisherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.publisher
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    long countByExample(PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.publisher
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int deleteByExample(PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.publisher
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.publisher
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int insert(Publisher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.publisher
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int insertSelective(Publisher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.publisher
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    List<Publisher> selectByExample(PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.publisher
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    Publisher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.publisher
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByExampleSelective(@Param("record") Publisher record, @Param("example") PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.publisher
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByExample(@Param("record") Publisher record, @Param("example") PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.publisher
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByPrimaryKeySelective(Publisher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.publisher
     *
     * @mbg.generated Sun May 24 00:30:09 JST 2020
     */
    int updateByPrimaryKey(Publisher record);
}